//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ykcd.SubAgency.Business.AgencyServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgencyServices.AgencyServicesSoap")]
    public interface AgencyServicesSoap {
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveRequest", ReplyAction="*")]
        Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponse ReceiveRequest(Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponse> ReceiveRequestAsync(Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest request);
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReport", ReplyAction="*")]
        Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponse ReceiveReport(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponse> ReceiveReportAsync(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRequest", ReplyAction="*")]
        void DeleteRequest(long requestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRequest", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteRequestAsync(long requestID);
        
        // CODEGEN: Generating message contract since element name GetRequestInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestInfo", ReplyAction="*")]
        Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponse GetRequestInfo(Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponse> GetRequestInfoAsync(Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllRequestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRequest", ReplyAction="*")]
        Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponse GetAllRequest(Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponse> GetAllRequestAsync(Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllReportResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllReport", ReplyAction="*")]
        Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponse GetAllReport(Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllReport", ReplyAction="*")]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponse> GetAllReportAsync(Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestSynced", ReplyAction="*")]
        void SetRequestSynced(long performID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestSynced", ReplyAction="*")]
        System.Threading.Tasks.Task SetRequestSyncedAsync(long performID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestStatus", ReplyAction="*")]
        void SetRequestStatus(long performID, int status, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestStatus", ReplyAction="*")]
        System.Threading.Tasks.Task SetRequestStatusAsync(long performID, int status, System.DateTime date);
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReportFromSubAgency", ReplyAction="*")]
        Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponse ReceiveReportFromSubAgency(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReportFromSubAgency", ReplyAction="*")]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponse> ReceiveReportFromSubAgencyAsync(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveRequest", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequestBody Body;
        
        public ReceiveRequestRequest() {
        }
        
        public ReceiveRequestRequest(Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveRequestRequestBody() {
        }
        
        public ReceiveRequestRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponseBody Body;
        
        public ReceiveRequestResponse() {
        }
        
        public ReceiveRequestResponse(Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveRequestResult;
        
        public ReceiveRequestResponseBody() {
        }
        
        public ReceiveRequestResponseBody(bool ReceiveRequestResult) {
            this.ReceiveRequestResult = ReceiveRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReport", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequestBody Body;
        
        public ReceiveReportRequest() {
        }
        
        public ReceiveReportRequest(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveReportRequestBody() {
        }
        
        public ReceiveReportRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponseBody Body;
        
        public ReceiveReportResponse() {
        }
        
        public ReceiveReportResponse(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveReportResult;
        
        public ReceiveReportResponseBody() {
        }
        
        public ReceiveReportResponseBody(bool ReceiveReportResult) {
            this.ReceiveReportResult = ReceiveReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequestInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequestInfo", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequestBody Body;
        
        public GetRequestInfoRequest() {
        }
        
        public GetRequestInfoRequest(Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int departmentID;
        
        public GetRequestInfoRequestBody() {
        }
        
        public GetRequestInfoRequestBody(long requestID, int departmentID) {
            this.requestID = requestID;
            this.departmentID = departmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequestInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequestInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponseBody Body;
        
        public GetRequestInfoResponse() {
        }
        
        public GetRequestInfoResponse(Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRequestInfoResult;
        
        public GetRequestInfoResponseBody() {
        }
        
        public GetRequestInfoResponseBody(string GetRequestInfoResult) {
            this.GetRequestInfoResult = GetRequestInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRequest", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequestBody Body;
        
        public GetAllRequestRequest() {
        }
        
        public GetAllRequestRequest(Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int departmentID;
        
        public GetAllRequestRequestBody() {
        }
        
        public GetAllRequestRequestBody(int departmentID) {
            this.departmentID = departmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponseBody Body;
        
        public GetAllRequestResponse() {
        }
        
        public GetAllRequestResponse(Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllRequestResult;
        
        public GetAllRequestResponseBody() {
        }
        
        public GetAllRequestResponseBody(string GetAllRequestResult) {
            this.GetAllRequestResult = GetAllRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReport", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequestBody Body;
        
        public GetAllReportRequest() {
        }
        
        public GetAllReportRequest(Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int agencyID;
        
        public GetAllReportRequestBody() {
        }
        
        public GetAllReportRequestBody(long requestID, int agencyID) {
            this.requestID = requestID;
            this.agencyID = agencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponseBody Body;
        
        public GetAllReportResponse() {
        }
        
        public GetAllReportResponse(Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllReportResult;
        
        public GetAllReportResponseBody() {
        }
        
        public GetAllReportResponseBody(string GetAllReportResult) {
            this.GetAllReportResult = GetAllReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportFromSubAgencyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportFromSubAgency", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequestBody Body;
        
        public ReceiveReportFromSubAgencyRequest() {
        }
        
        public ReceiveReportFromSubAgencyRequest(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportFromSubAgencyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveReportFromSubAgencyRequestBody() {
        }
        
        public ReceiveReportFromSubAgencyRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportFromSubAgencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportFromSubAgencyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponseBody Body;
        
        public ReceiveReportFromSubAgencyResponse() {
        }
        
        public ReceiveReportFromSubAgencyResponse(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportFromSubAgencyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveReportFromSubAgencyResult;
        
        public ReceiveReportFromSubAgencyResponseBody() {
        }
        
        public ReceiveReportFromSubAgencyResponseBody(bool ReceiveReportFromSubAgencyResult) {
            this.ReceiveReportFromSubAgencyResult = ReceiveReportFromSubAgencyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgencyServicesSoapChannel : Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgencyServicesSoapClient : System.ServiceModel.ClientBase<Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap>, Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap {
        
        public AgencyServicesSoapClient() {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponse Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.ReceiveRequest(Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest request) {
            return base.Channel.ReceiveRequest(request);
        }
        
        public bool ReceiveRequest(string xmlDoc) {
            Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponse retVal = ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).ReceiveRequest(inValue);
            return retVal.Body.ReceiveRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponse> Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.ReceiveRequestAsync(Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest request) {
            return base.Channel.ReceiveRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestResponse> ReceiveRequestAsync(string xmlDoc) {
            Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.ReceiveRequestRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            return ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).ReceiveRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponse Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.ReceiveReport(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest request) {
            return base.Channel.ReceiveReport(request);
        }
        
        public bool ReceiveReport(string xmlDoc) {
            Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponse retVal = ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).ReceiveReport(inValue);
            return retVal.Body.ReceiveReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponse> Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.ReceiveReportAsync(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest request) {
            return base.Channel.ReceiveReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveReportResponse> ReceiveReportAsync(string xmlDoc) {
            Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            return ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).ReceiveReportAsync(inValue);
        }
        
        public void DeleteRequest(long requestID) {
            base.Channel.DeleteRequest(requestID);
        }
        
        public System.Threading.Tasks.Task DeleteRequestAsync(long requestID) {
            return base.Channel.DeleteRequestAsync(requestID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponse Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.GetRequestInfo(Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest request) {
            return base.Channel.GetRequestInfo(request);
        }
        
        public string GetRequestInfo(long requestID, int departmentID) {
            Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.departmentID = departmentID;
            Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponse retVal = ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).GetRequestInfo(inValue);
            return retVal.Body.GetRequestInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponse> Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.GetRequestInfoAsync(Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest request) {
            return base.Channel.GetRequestInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoResponse> GetRequestInfoAsync(long requestID, int departmentID) {
            Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.GetRequestInfoRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.departmentID = departmentID;
            return ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).GetRequestInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponse Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.GetAllRequest(Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest request) {
            return base.Channel.GetAllRequest(request);
        }
        
        public string GetAllRequest(int departmentID) {
            Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequestBody();
            inValue.Body.departmentID = departmentID;
            Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponse retVal = ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).GetAllRequest(inValue);
            return retVal.Body.GetAllRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponse> Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.GetAllRequestAsync(Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest request) {
            return base.Channel.GetAllRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetAllRequestResponse> GetAllRequestAsync(int departmentID) {
            Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.GetAllRequestRequestBody();
            inValue.Body.departmentID = departmentID;
            return ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).GetAllRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponse Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.GetAllReport(Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest request) {
            return base.Channel.GetAllReport(request);
        }
        
        public string GetAllReport(long requestID, int agencyID) {
            Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.agencyID = agencyID;
            Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponse retVal = ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).GetAllReport(inValue);
            return retVal.Body.GetAllReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponse> Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.GetAllReportAsync(Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest request) {
            return base.Channel.GetAllReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.GetAllReportResponse> GetAllReportAsync(long requestID, int agencyID) {
            Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.GetAllReportRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.agencyID = agencyID;
            return ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).GetAllReportAsync(inValue);
        }
        
        public void SetRequestSynced(long performID) {
            base.Channel.SetRequestSynced(performID);
        }
        
        public System.Threading.Tasks.Task SetRequestSyncedAsync(long performID) {
            return base.Channel.SetRequestSyncedAsync(performID);
        }
        
        public void SetRequestStatus(long performID, int status, System.DateTime date) {
            base.Channel.SetRequestStatus(performID, status, date);
        }
        
        public System.Threading.Tasks.Task SetRequestStatusAsync(long performID, int status, System.DateTime date) {
            return base.Channel.SetRequestStatusAsync(performID, status, date);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponse Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.ReceiveReportFromSubAgency(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest request) {
            return base.Channel.ReceiveReportFromSubAgency(request);
        }
        
        public bool ReceiveReportFromSubAgency(string xmlDoc) {
            Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponse retVal = ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).ReceiveReportFromSubAgency(inValue);
            return retVal.Body.ReceiveReportFromSubAgencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponse> Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap.ReceiveReportFromSubAgencyAsync(Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest request) {
            return base.Channel.ReceiveReportFromSubAgencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyResponse> ReceiveReportFromSubAgencyAsync(string xmlDoc) {
            Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest inValue = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequest();
            inValue.Body = new Ykcd.SubAgency.Business.AgencyServices.ReceiveReportFromSubAgencyRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            return ((Ykcd.SubAgency.Business.AgencyServices.AgencyServicesSoap)(this)).ReceiveReportFromSubAgencyAsync(inValue);
        }
    }
}
