//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKCD.Agency.Business.ProvinceService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VanBanChiDao", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VanBanChiDao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaVanBanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KyHieuField;
        
        private System.DateTime NgayBanHanhField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NguoiKyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NguoiSoanThaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrichYeuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YKCD.Agency.Business.ProvinceService.FileDinhKem[] DsFileDinhKemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MaVanBan {
            get {
                return this.MaVanBanField;
            }
            set {
                if ((object.ReferenceEquals(this.MaVanBanField, value) != true)) {
                    this.MaVanBanField = value;
                    this.RaisePropertyChanged("MaVanBan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KyHieu {
            get {
                return this.KyHieuField;
            }
            set {
                if ((object.ReferenceEquals(this.KyHieuField, value) != true)) {
                    this.KyHieuField = value;
                    this.RaisePropertyChanged("KyHieu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime NgayBanHanh {
            get {
                return this.NgayBanHanhField;
            }
            set {
                if ((this.NgayBanHanhField.Equals(value) != true)) {
                    this.NgayBanHanhField = value;
                    this.RaisePropertyChanged("NgayBanHanh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NguoiKy {
            get {
                return this.NguoiKyField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiKyField, value) != true)) {
                    this.NguoiKyField = value;
                    this.RaisePropertyChanged("NguoiKy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string NguoiSoanThao {
            get {
                return this.NguoiSoanThaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NguoiSoanThaoField, value) != true)) {
                    this.NguoiSoanThaoField = value;
                    this.RaisePropertyChanged("NguoiSoanThao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TrichYeu {
            get {
                return this.TrichYeuField;
            }
            set {
                if ((object.ReferenceEquals(this.TrichYeuField, value) != true)) {
                    this.TrichYeuField = value;
                    this.RaisePropertyChanged("TrichYeu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public YKCD.Agency.Business.ProvinceService.FileDinhKem[] DsFileDinhKem {
            get {
                return this.DsFileDinhKemField;
            }
            set {
                if ((object.ReferenceEquals(this.DsFileDinhKemField, value) != true)) {
                    this.DsFileDinhKemField = value;
                    this.RaisePropertyChanged("DsFileDinhKem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDinhKem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FileDinhKem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YKienChiDao", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class YKienChiDao : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoiDungThucHienField;
        
        private System.DateTime ThoiHanThucHienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YKCD.Agency.Business.ProvinceService.ArrayOfString DsDonViThucHienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private YKCD.Agency.Business.ProvinceService.ArrayOfString DsChuyenVienTheoDoiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NoiDungThucHien {
            get {
                return this.NoiDungThucHienField;
            }
            set {
                if ((object.ReferenceEquals(this.NoiDungThucHienField, value) != true)) {
                    this.NoiDungThucHienField = value;
                    this.RaisePropertyChanged("NoiDungThucHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime ThoiHanThucHien {
            get {
                return this.ThoiHanThucHienField;
            }
            set {
                if ((this.ThoiHanThucHienField.Equals(value) != true)) {
                    this.ThoiHanThucHienField = value;
                    this.RaisePropertyChanged("ThoiHanThucHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public YKCD.Agency.Business.ProvinceService.ArrayOfString DsDonViThucHien {
            get {
                return this.DsDonViThucHienField;
            }
            set {
                if ((object.ReferenceEquals(this.DsDonViThucHienField, value) != true)) {
                    this.DsDonViThucHienField = value;
                    this.RaisePropertyChanged("DsDonViThucHien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public YKCD.Agency.Business.ProvinceService.ArrayOfString DsChuyenVienTheoDoi {
            get {
                return this.DsChuyenVienTheoDoiField;
            }
            set {
                if ((object.ReferenceEquals(this.DsChuyenVienTheoDoiField, value) != true)) {
                    this.DsChuyenVienTheoDoiField = value;
                    this.RaisePropertyChanged("DsChuyenVienTheoDoi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProvinceService.ProvinceServiceSoap")]
    public interface ProvinceServiceSoap {
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReport", ReplyAction="*")]
        YKCD.Agency.Business.ProvinceService.ReceiveReportResponse ReceiveReport(YKCD.Agency.Business.ProvinceService.ReceiveReportRequest request);
        
        // CODEGEN: Generating message contract since element name GetRequestInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestInfo", ReplyAction="*")]
        YKCD.Agency.Business.ProvinceService.GetRequestInfoResponse GetRequestInfo(YKCD.Agency.Business.ProvinceService.GetRequestInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllRequestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRequest", ReplyAction="*")]
        YKCD.Agency.Business.ProvinceService.GetAllRequestResponse GetAllRequest(YKCD.Agency.Business.ProvinceService.GetAllRequestRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllReportResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllReport", ReplyAction="*")]
        YKCD.Agency.Business.ProvinceService.GetAllReportResponse GetAllReport(YKCD.Agency.Business.ProvinceService.GetAllReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestSynced", ReplyAction="*")]
        void SetRequestSynced(long performID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestStatus", ReplyAction="*")]
        int SetRequestStatus(long performID, int status, System.DateTime date);
        
        // CODEGEN: Generating message contract since element name vanBan from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRequest", ReplyAction="*")]
        YKCD.Agency.Business.ProvinceService.CreateRequestResponse CreateRequest(YKCD.Agency.Business.ProvinceService.CreateRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReport", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.ReceiveReportRequestBody Body;
        
        public ReceiveReportRequest() {
        }
        
        public ReceiveReportRequest(YKCD.Agency.Business.ProvinceService.ReceiveReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveReportRequestBody() {
        }
        
        public ReceiveReportRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.ReceiveReportResponseBody Body;
        
        public ReceiveReportResponse() {
        }
        
        public ReceiveReportResponse(YKCD.Agency.Business.ProvinceService.ReceiveReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveReportResult;
        
        public ReceiveReportResponseBody() {
        }
        
        public ReceiveReportResponseBody(bool ReceiveReportResult) {
            this.ReceiveReportResult = ReceiveReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequestInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequestInfo", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.GetRequestInfoRequestBody Body;
        
        public GetRequestInfoRequest() {
        }
        
        public GetRequestInfoRequest(YKCD.Agency.Business.ProvinceService.GetRequestInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int agencyID;
        
        public GetRequestInfoRequestBody() {
        }
        
        public GetRequestInfoRequestBody(long requestID, int agencyID) {
            this.requestID = requestID;
            this.agencyID = agencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequestInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequestInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.GetRequestInfoResponseBody Body;
        
        public GetRequestInfoResponse() {
        }
        
        public GetRequestInfoResponse(YKCD.Agency.Business.ProvinceService.GetRequestInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRequestInfoResult;
        
        public GetRequestInfoResponseBody() {
        }
        
        public GetRequestInfoResponseBody(string GetRequestInfoResult) {
            this.GetRequestInfoResult = GetRequestInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRequest", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.GetAllRequestRequestBody Body;
        
        public GetAllRequestRequest() {
        }
        
        public GetAllRequestRequest(YKCD.Agency.Business.ProvinceService.GetAllRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int agencyID;
        
        public GetAllRequestRequestBody() {
        }
        
        public GetAllRequestRequestBody(int agencyID) {
            this.agencyID = agencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.GetAllRequestResponseBody Body;
        
        public GetAllRequestResponse() {
        }
        
        public GetAllRequestResponse(YKCD.Agency.Business.ProvinceService.GetAllRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllRequestResult;
        
        public GetAllRequestResponseBody() {
        }
        
        public GetAllRequestResponseBody(string GetAllRequestResult) {
            this.GetAllRequestResult = GetAllRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReport", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.GetAllReportRequestBody Body;
        
        public GetAllReportRequest() {
        }
        
        public GetAllReportRequest(YKCD.Agency.Business.ProvinceService.GetAllReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int agencyID;
        
        public GetAllReportRequestBody() {
        }
        
        public GetAllReportRequestBody(long requestID, int agencyID) {
            this.requestID = requestID;
            this.agencyID = agencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.GetAllReportResponseBody Body;
        
        public GetAllReportResponse() {
        }
        
        public GetAllReportResponse(YKCD.Agency.Business.ProvinceService.GetAllReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllReportResult;
        
        public GetAllReportResponseBody() {
        }
        
        public GetAllReportResponseBody(string GetAllReportResult) {
            this.GetAllReportResult = GetAllReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRequest", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.CreateRequestRequestBody Body;
        
        public CreateRequestRequest() {
        }
        
        public CreateRequestRequest(YKCD.Agency.Business.ProvinceService.CreateRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YKCD.Agency.Business.ProvinceService.VanBanChiDao vanBan;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public YKCD.Agency.Business.ProvinceService.YKienChiDao[] dsYKienChiDao;
        
        public CreateRequestRequestBody() {
        }
        
        public CreateRequestRequestBody(YKCD.Agency.Business.ProvinceService.VanBanChiDao vanBan, YKCD.Agency.Business.ProvinceService.YKienChiDao[] dsYKienChiDao) {
            this.vanBan = vanBan;
            this.dsYKienChiDao = dsYKienChiDao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Agency.Business.ProvinceService.CreateRequestResponseBody Body;
        
        public CreateRequestResponse() {
        }
        
        public CreateRequestResponse(YKCD.Agency.Business.ProvinceService.CreateRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateRequestResult;
        
        public CreateRequestResponseBody() {
        }
        
        public CreateRequestResponseBody(bool CreateRequestResult) {
            this.CreateRequestResult = CreateRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProvinceServiceSoapChannel : YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProvinceServiceSoapClient : System.ServiceModel.ClientBase<YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap>, YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap {
        
        public ProvinceServiceSoapClient() {
        }
        
        public ProvinceServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProvinceServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvinceServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProvinceServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.Agency.Business.ProvinceService.ReceiveReportResponse YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap.ReceiveReport(YKCD.Agency.Business.ProvinceService.ReceiveReportRequest request) {
            return base.Channel.ReceiveReport(request);
        }
        
        public bool ReceiveReport(string xmlDoc) {
            YKCD.Agency.Business.ProvinceService.ReceiveReportRequest inValue = new YKCD.Agency.Business.ProvinceService.ReceiveReportRequest();
            inValue.Body = new YKCD.Agency.Business.ProvinceService.ReceiveReportRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            YKCD.Agency.Business.ProvinceService.ReceiveReportResponse retVal = ((YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap)(this)).ReceiveReport(inValue);
            return retVal.Body.ReceiveReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.Agency.Business.ProvinceService.GetRequestInfoResponse YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap.GetRequestInfo(YKCD.Agency.Business.ProvinceService.GetRequestInfoRequest request) {
            return base.Channel.GetRequestInfo(request);
        }
        
        public string GetRequestInfo(long requestID, int agencyID) {
            YKCD.Agency.Business.ProvinceService.GetRequestInfoRequest inValue = new YKCD.Agency.Business.ProvinceService.GetRequestInfoRequest();
            inValue.Body = new YKCD.Agency.Business.ProvinceService.GetRequestInfoRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.agencyID = agencyID;
            YKCD.Agency.Business.ProvinceService.GetRequestInfoResponse retVal = ((YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap)(this)).GetRequestInfo(inValue);
            return retVal.Body.GetRequestInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.Agency.Business.ProvinceService.GetAllRequestResponse YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap.GetAllRequest(YKCD.Agency.Business.ProvinceService.GetAllRequestRequest request) {
            return base.Channel.GetAllRequest(request);
        }
        
        public string GetAllRequest(int agencyID) {
            YKCD.Agency.Business.ProvinceService.GetAllRequestRequest inValue = new YKCD.Agency.Business.ProvinceService.GetAllRequestRequest();
            inValue.Body = new YKCD.Agency.Business.ProvinceService.GetAllRequestRequestBody();
            inValue.Body.agencyID = agencyID;
            YKCD.Agency.Business.ProvinceService.GetAllRequestResponse retVal = ((YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap)(this)).GetAllRequest(inValue);
            return retVal.Body.GetAllRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.Agency.Business.ProvinceService.GetAllReportResponse YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap.GetAllReport(YKCD.Agency.Business.ProvinceService.GetAllReportRequest request) {
            return base.Channel.GetAllReport(request);
        }
        
        public string GetAllReport(long requestID, int agencyID) {
            YKCD.Agency.Business.ProvinceService.GetAllReportRequest inValue = new YKCD.Agency.Business.ProvinceService.GetAllReportRequest();
            inValue.Body = new YKCD.Agency.Business.ProvinceService.GetAllReportRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.agencyID = agencyID;
            YKCD.Agency.Business.ProvinceService.GetAllReportResponse retVal = ((YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap)(this)).GetAllReport(inValue);
            return retVal.Body.GetAllReportResult;
        }
        
        public void SetRequestSynced(long performID) {
            base.Channel.SetRequestSynced(performID);
        }
        
        public int SetRequestStatus(long performID, int status, System.DateTime date) {
            return base.Channel.SetRequestStatus(performID, status, date);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.Agency.Business.ProvinceService.CreateRequestResponse YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap.CreateRequest(YKCD.Agency.Business.ProvinceService.CreateRequestRequest request) {
            return base.Channel.CreateRequest(request);
        }
        
        public bool CreateRequest(YKCD.Agency.Business.ProvinceService.VanBanChiDao vanBan, YKCD.Agency.Business.ProvinceService.YKienChiDao[] dsYKienChiDao) {
            YKCD.Agency.Business.ProvinceService.CreateRequestRequest inValue = new YKCD.Agency.Business.ProvinceService.CreateRequestRequest();
            inValue.Body = new YKCD.Agency.Business.ProvinceService.CreateRequestRequestBody();
            inValue.Body.vanBan = vanBan;
            inValue.Body.dsYKienChiDao = dsYKienChiDao;
            YKCD.Agency.Business.ProvinceService.CreateRequestResponse retVal = ((YKCD.Agency.Business.ProvinceService.ProvinceServiceSoap)(this)).CreateRequest(inValue);
            return retVal.Body.CreateRequestResult;
        }
    }
}
