//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKCD.Province.Business.AgencyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgencyService.AgencyServicesSoap")]
    public interface AgencyServicesSoap {
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveRequest", ReplyAction="*")]
        YKCD.Province.Business.AgencyService.ReceiveRequestResponse ReceiveRequest(YKCD.Province.Business.AgencyService.ReceiveRequestRequest request);
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReport", ReplyAction="*")]
        YKCD.Province.Business.AgencyService.ReceiveReportResponse ReceiveReport(YKCD.Province.Business.AgencyService.ReceiveReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRequest", ReplyAction="*")]
        void DeleteRequest(long requestID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveRequest", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Province.Business.AgencyService.ReceiveRequestRequestBody Body;
        
        public ReceiveRequestRequest() {
        }
        
        public ReceiveRequestRequest(YKCD.Province.Business.AgencyService.ReceiveRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveRequestRequestBody() {
        }
        
        public ReceiveRequestRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Province.Business.AgencyService.ReceiveRequestResponseBody Body;
        
        public ReceiveRequestResponse() {
        }
        
        public ReceiveRequestResponse(YKCD.Province.Business.AgencyService.ReceiveRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveRequestResult;
        
        public ReceiveRequestResponseBody() {
        }
        
        public ReceiveRequestResponseBody(bool ReceiveRequestResult) {
            this.ReceiveRequestResult = ReceiveRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReport", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Province.Business.AgencyService.ReceiveReportRequestBody Body;
        
        public ReceiveReportRequest() {
        }
        
        public ReceiveReportRequest(YKCD.Province.Business.AgencyService.ReceiveReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveReportRequestBody() {
        }
        
        public ReceiveReportRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.Province.Business.AgencyService.ReceiveReportResponseBody Body;
        
        public ReceiveReportResponse() {
        }
        
        public ReceiveReportResponse(YKCD.Province.Business.AgencyService.ReceiveReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveReportResult;
        
        public ReceiveReportResponseBody() {
        }
        
        public ReceiveReportResponseBody(bool ReceiveReportResult) {
            this.ReceiveReportResult = ReceiveReportResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgencyServicesSoapChannel : YKCD.Province.Business.AgencyService.AgencyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgencyServicesSoapClient : System.ServiceModel.ClientBase<YKCD.Province.Business.AgencyService.AgencyServicesSoap>, YKCD.Province.Business.AgencyService.AgencyServicesSoap {
        
        public AgencyServicesSoapClient() {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.Province.Business.AgencyService.ReceiveRequestResponse YKCD.Province.Business.AgencyService.AgencyServicesSoap.ReceiveRequest(YKCD.Province.Business.AgencyService.ReceiveRequestRequest request) {
            return base.Channel.ReceiveRequest(request);
        }
        
        public bool ReceiveRequest(string xmlDoc) {
            YKCD.Province.Business.AgencyService.ReceiveRequestRequest inValue = new YKCD.Province.Business.AgencyService.ReceiveRequestRequest();
            inValue.Body = new YKCD.Province.Business.AgencyService.ReceiveRequestRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            YKCD.Province.Business.AgencyService.ReceiveRequestResponse retVal = ((YKCD.Province.Business.AgencyService.AgencyServicesSoap)(this)).ReceiveRequest(inValue);
            return retVal.Body.ReceiveRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.Province.Business.AgencyService.ReceiveReportResponse YKCD.Province.Business.AgencyService.AgencyServicesSoap.ReceiveReport(YKCD.Province.Business.AgencyService.ReceiveReportRequest request) {
            return base.Channel.ReceiveReport(request);
        }
        
        public bool ReceiveReport(string xmlDoc) {
            YKCD.Province.Business.AgencyService.ReceiveReportRequest inValue = new YKCD.Province.Business.AgencyService.ReceiveReportRequest();
            inValue.Body = new YKCD.Province.Business.AgencyService.ReceiveReportRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            YKCD.Province.Business.AgencyService.ReceiveReportResponse retVal = ((YKCD.Province.Business.AgencyService.AgencyServicesSoap)(this)).ReceiveReport(inValue);
            return retVal.Body.ReceiveReportResult;
        }
        
        public void DeleteRequest(long requestID) {
            base.Channel.DeleteRequest(requestID);
        }
    }
}
