//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKCD.SubAgency.Application.AgencyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgencyService.AgencyServicesSoap")]
    public interface AgencyServicesSoap {
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveRequest", ReplyAction="*")]
        YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponse ReceiveRequest(YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponse> ReceiveRequestAsync(YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest request);
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReport", ReplyAction="*")]
        YKCD.SubAgency.Application.AgencyService.ReceiveReportResponse ReceiveReport(YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReport", ReplyAction="*")]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveReportResponse> ReceiveReportAsync(YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRequest", ReplyAction="*")]
        void DeleteRequest(long requestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRequest", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteRequestAsync(long requestID);
        
        // CODEGEN: Generating message contract since element name GetRequestInfoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestInfo", ReplyAction="*")]
        YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponse GetRequestInfo(YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRequestInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponse> GetRequestInfoAsync(YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllRequestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRequest", ReplyAction="*")]
        YKCD.SubAgency.Application.AgencyService.GetAllRequestResponse GetAllRequest(YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetAllRequestResponse> GetAllRequestAsync(YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllReportResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllReport", ReplyAction="*")]
        YKCD.SubAgency.Application.AgencyService.GetAllReportResponse GetAllReport(YKCD.SubAgency.Application.AgencyService.GetAllReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllReport", ReplyAction="*")]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetAllReportResponse> GetAllReportAsync(YKCD.SubAgency.Application.AgencyService.GetAllReportRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestSynced", ReplyAction="*")]
        void SetRequestSynced(long performID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestSynced", ReplyAction="*")]
        System.Threading.Tasks.Task SetRequestSyncedAsync(long performID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestStatus", ReplyAction="*")]
        void SetRequestStatus(long performID, int status, System.DateTime date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetRequestStatus", ReplyAction="*")]
        System.Threading.Tasks.Task SetRequestStatusAsync(long performID, int status, System.DateTime date);
        
        // CODEGEN: Generating message contract since element name xmlDoc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReportFromSubAgency", ReplyAction="*")]
        YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponse ReceiveReportFromSubAgency(YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveReportFromSubAgency", ReplyAction="*")]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponse> ReceiveReportFromSubAgencyAsync(YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveRequest", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequestBody Body;
        
        public ReceiveRequestRequest() {
        }
        
        public ReceiveRequestRequest(YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveRequestRequestBody() {
        }
        
        public ReceiveRequestRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponseBody Body;
        
        public ReceiveRequestResponse() {
        }
        
        public ReceiveRequestResponse(YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveRequestResult;
        
        public ReceiveRequestResponseBody() {
        }
        
        public ReceiveRequestResponseBody(bool ReceiveRequestResult) {
            this.ReceiveRequestResult = ReceiveRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReport", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.ReceiveReportRequestBody Body;
        
        public ReceiveReportRequest() {
        }
        
        public ReceiveReportRequest(YKCD.SubAgency.Application.AgencyService.ReceiveReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveReportRequestBody() {
        }
        
        public ReceiveReportRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.ReceiveReportResponseBody Body;
        
        public ReceiveReportResponse() {
        }
        
        public ReceiveReportResponse(YKCD.SubAgency.Application.AgencyService.ReceiveReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveReportResult;
        
        public ReceiveReportResponseBody() {
        }
        
        public ReceiveReportResponseBody(bool ReceiveReportResult) {
            this.ReceiveReportResult = ReceiveReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequestInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequestInfo", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequestBody Body;
        
        public GetRequestInfoRequest() {
        }
        
        public GetRequestInfoRequest(YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int departmentID;
        
        public GetRequestInfoRequestBody() {
        }
        
        public GetRequestInfoRequestBody(long requestID, int departmentID) {
            this.requestID = requestID;
            this.departmentID = departmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequestInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRequestInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponseBody Body;
        
        public GetRequestInfoResponse() {
        }
        
        public GetRequestInfoResponse(YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRequestInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRequestInfoResult;
        
        public GetRequestInfoResponseBody() {
        }
        
        public GetRequestInfoResponseBody(string GetRequestInfoResult) {
            this.GetRequestInfoResult = GetRequestInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRequest", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.GetAllRequestRequestBody Body;
        
        public GetAllRequestRequest() {
        }
        
        public GetAllRequestRequest(YKCD.SubAgency.Application.AgencyService.GetAllRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int departmentID;
        
        public GetAllRequestRequestBody() {
        }
        
        public GetAllRequestRequestBody(int departmentID) {
            this.departmentID = departmentID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.GetAllRequestResponseBody Body;
        
        public GetAllRequestResponse() {
        }
        
        public GetAllRequestResponse(YKCD.SubAgency.Application.AgencyService.GetAllRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllRequestResult;
        
        public GetAllRequestResponseBody() {
        }
        
        public GetAllRequestResponseBody(string GetAllRequestResult) {
            this.GetAllRequestResult = GetAllRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReportRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReport", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.GetAllReportRequestBody Body;
        
        public GetAllReportRequest() {
        }
        
        public GetAllReportRequest(YKCD.SubAgency.Application.AgencyService.GetAllReportRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReportRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long requestID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int agencyID;
        
        public GetAllReportRequestBody() {
        }
        
        public GetAllReportRequestBody(long requestID, int agencyID) {
            this.requestID = requestID;
            this.agencyID = agencyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReportResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReportResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.GetAllReportResponseBody Body;
        
        public GetAllReportResponse() {
        }
        
        public GetAllReportResponse(YKCD.SubAgency.Application.AgencyService.GetAllReportResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReportResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllReportResult;
        
        public GetAllReportResponseBody() {
        }
        
        public GetAllReportResponseBody(string GetAllReportResult) {
            this.GetAllReportResult = GetAllReportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportFromSubAgencyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportFromSubAgency", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequestBody Body;
        
        public ReceiveReportFromSubAgencyRequest() {
        }
        
        public ReceiveReportFromSubAgencyRequest(YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportFromSubAgencyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public ReceiveReportFromSubAgencyRequestBody() {
        }
        
        public ReceiveReportFromSubAgencyRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveReportFromSubAgencyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveReportFromSubAgencyResponse", Namespace="http://tempuri.org/", Order=0)]
        public YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponseBody Body;
        
        public ReceiveReportFromSubAgencyResponse() {
        }
        
        public ReceiveReportFromSubAgencyResponse(YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveReportFromSubAgencyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ReceiveReportFromSubAgencyResult;
        
        public ReceiveReportFromSubAgencyResponseBody() {
        }
        
        public ReceiveReportFromSubAgencyResponseBody(bool ReceiveReportFromSubAgencyResult) {
            this.ReceiveReportFromSubAgencyResult = ReceiveReportFromSubAgencyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgencyServicesSoapChannel : YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgencyServicesSoapClient : System.ServiceModel.ClientBase<YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap>, YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap {
        
        public AgencyServicesSoapClient() {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgencyServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponse YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.ReceiveRequest(YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest request) {
            return base.Channel.ReceiveRequest(request);
        }
        
        public bool ReceiveRequest(string xmlDoc) {
            YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest inValue = new YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponse retVal = ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).ReceiveRequest(inValue);
            return retVal.Body.ReceiveRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponse> YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.ReceiveRequestAsync(YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest request) {
            return base.Channel.ReceiveRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveRequestResponse> ReceiveRequestAsync(string xmlDoc) {
            YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest inValue = new YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.ReceiveRequestRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            return ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).ReceiveRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.SubAgency.Application.AgencyService.ReceiveReportResponse YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.ReceiveReport(YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest request) {
            return base.Channel.ReceiveReport(request);
        }
        
        public bool ReceiveReport(string xmlDoc) {
            YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest inValue = new YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.ReceiveReportRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            YKCD.SubAgency.Application.AgencyService.ReceiveReportResponse retVal = ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).ReceiveReport(inValue);
            return retVal.Body.ReceiveReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveReportResponse> YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.ReceiveReportAsync(YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest request) {
            return base.Channel.ReceiveReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveReportResponse> ReceiveReportAsync(string xmlDoc) {
            YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest inValue = new YKCD.SubAgency.Application.AgencyService.ReceiveReportRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.ReceiveReportRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            return ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).ReceiveReportAsync(inValue);
        }
        
        public void DeleteRequest(long requestID) {
            base.Channel.DeleteRequest(requestID);
        }
        
        public System.Threading.Tasks.Task DeleteRequestAsync(long requestID) {
            return base.Channel.DeleteRequestAsync(requestID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponse YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.GetRequestInfo(YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest request) {
            return base.Channel.GetRequestInfo(request);
        }
        
        public string GetRequestInfo(long requestID, int departmentID) {
            YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest inValue = new YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.departmentID = departmentID;
            YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponse retVal = ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).GetRequestInfo(inValue);
            return retVal.Body.GetRequestInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponse> YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.GetRequestInfoAsync(YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest request) {
            return base.Channel.GetRequestInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetRequestInfoResponse> GetRequestInfoAsync(long requestID, int departmentID) {
            YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest inValue = new YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.GetRequestInfoRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.departmentID = departmentID;
            return ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).GetRequestInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.SubAgency.Application.AgencyService.GetAllRequestResponse YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.GetAllRequest(YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest request) {
            return base.Channel.GetAllRequest(request);
        }
        
        public string GetAllRequest(int departmentID) {
            YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest inValue = new YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.GetAllRequestRequestBody();
            inValue.Body.departmentID = departmentID;
            YKCD.SubAgency.Application.AgencyService.GetAllRequestResponse retVal = ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).GetAllRequest(inValue);
            return retVal.Body.GetAllRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetAllRequestResponse> YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.GetAllRequestAsync(YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest request) {
            return base.Channel.GetAllRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetAllRequestResponse> GetAllRequestAsync(int departmentID) {
            YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest inValue = new YKCD.SubAgency.Application.AgencyService.GetAllRequestRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.GetAllRequestRequestBody();
            inValue.Body.departmentID = departmentID;
            return ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).GetAllRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.SubAgency.Application.AgencyService.GetAllReportResponse YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.GetAllReport(YKCD.SubAgency.Application.AgencyService.GetAllReportRequest request) {
            return base.Channel.GetAllReport(request);
        }
        
        public string GetAllReport(long requestID, int agencyID) {
            YKCD.SubAgency.Application.AgencyService.GetAllReportRequest inValue = new YKCD.SubAgency.Application.AgencyService.GetAllReportRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.GetAllReportRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.agencyID = agencyID;
            YKCD.SubAgency.Application.AgencyService.GetAllReportResponse retVal = ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).GetAllReport(inValue);
            return retVal.Body.GetAllReportResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetAllReportResponse> YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.GetAllReportAsync(YKCD.SubAgency.Application.AgencyService.GetAllReportRequest request) {
            return base.Channel.GetAllReportAsync(request);
        }
        
        public System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.GetAllReportResponse> GetAllReportAsync(long requestID, int agencyID) {
            YKCD.SubAgency.Application.AgencyService.GetAllReportRequest inValue = new YKCD.SubAgency.Application.AgencyService.GetAllReportRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.GetAllReportRequestBody();
            inValue.Body.requestID = requestID;
            inValue.Body.agencyID = agencyID;
            return ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).GetAllReportAsync(inValue);
        }
        
        public void SetRequestSynced(long performID) {
            base.Channel.SetRequestSynced(performID);
        }
        
        public System.Threading.Tasks.Task SetRequestSyncedAsync(long performID) {
            return base.Channel.SetRequestSyncedAsync(performID);
        }
        
        public void SetRequestStatus(long performID, int status, System.DateTime date) {
            base.Channel.SetRequestStatus(performID, status, date);
        }
        
        public System.Threading.Tasks.Task SetRequestStatusAsync(long performID, int status, System.DateTime date) {
            return base.Channel.SetRequestStatusAsync(performID, status, date);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponse YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.ReceiveReportFromSubAgency(YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest request) {
            return base.Channel.ReceiveReportFromSubAgency(request);
        }
        
        public bool ReceiveReportFromSubAgency(string xmlDoc) {
            YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest inValue = new YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponse retVal = ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).ReceiveReportFromSubAgency(inValue);
            return retVal.Body.ReceiveReportFromSubAgencyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponse> YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap.ReceiveReportFromSubAgencyAsync(YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest request) {
            return base.Channel.ReceiveReportFromSubAgencyAsync(request);
        }
        
        public System.Threading.Tasks.Task<YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyResponse> ReceiveReportFromSubAgencyAsync(string xmlDoc) {
            YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest inValue = new YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequest();
            inValue.Body = new YKCD.SubAgency.Application.AgencyService.ReceiveReportFromSubAgencyRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            return ((YKCD.SubAgency.Application.AgencyService.AgencyServicesSoap)(this)).ReceiveReportFromSubAgencyAsync(inValue);
        }
    }
}
